### ISSUE TITLE
MM's wolf houling (And probably the whole module) works whilst in the End or Nether.

### ISSUE THREAD

**Issue by MagmaBro123** [Gamemode4Dev/GM4_Datapacks#286]
### Expected Behavior

The module only effecting the overworld.

### Current Behavior

Title says it all.
### Steps to Reproduce

1.
2.
3.
etc.
Install MM. Easy.
### Environment

Currently on a 1.14.4 Paper server, but Gamemode 4 datapacks aren't really being effected. MM itself is the issue.

**Comment by Bloo-dev** [comment]
@BluePsychoRanger did we potentially fix this during the rewrite?

**Comment by BluePsychoRanger** [comment]
> @BluePsychoRanger did we potentially fix this during the rewrite?

I just checked the code and we didn't fix this bug. Midnight Menaces also has this bug. The following functions should be modified to fix this bug:
1. Line 11 of `gm4_mysterious_midnights:calculate_difficulty` should be modified to only howl at `@a[x=0]`
2. Line 6 of `gm4_falling_stars:find_location` may have to be changed to `@r[x=0,gamemode=!spectator]`, though I've never seen this cause issues. Line 18 of `gm4_falling_stars:event` should say `@a[x=0,limit=1]` since it shouldn't run if there's no players in the overworked.
3. Line 5 of `gm4_resurrecting_skeletons:event` should have `@e[type=item,x=0,nbt={Item:{id:"minecraft:bone"},OnGround:1b}]`
4. Line 5 of `gm4_resurrecting_zombies:event` should have `@e[type=item,x=0,nbt={Item:{id:"minecraft:rotten_flesh"},OnGround:1b}]`
5. Line 5 of `gm4_tipped_skeletons:event` should have `@e[type=skeleton,tag=!gm4_tipped_skeleton,x=0,nbt={HandItems:[{id:"minecraft:bow",Count:1b},{}],PersistenceRequired:0b}]`

**Comment by MagmaBro123** [comment]
2 years later, lmao. XD (Sorry, but just saying)
