### ISSUE TITLE
Cooler Caves replaces nether portal with water

### ISSUE THREAD

**Issue by iFuzion77** [Gamemode4Dev/GM4_Datapacks#325]
When entering a new part of the world, from the nether to the overworld, the nether portal gets replaced by the cooler caves module with water in snowy biomes.

1 - Build a nether portal in the nether where a snowy biome would be in the overworld
2 - Go through the portal
3 - In the overworld, the portal should be replaced with water once Orbis and Cooler Caves ahs processed the chunk

**Expected behavior**
Nether portal not replaced by water

**Fix**
Not sure

**Environment**
 - Minecraft version: 1.14.4
 - Installed Datapacks: Orbis, Cooler Caves, & some others

**Additional context**
I used the seed 113318802, I think the world was generated in 1.13, but I'm now playing it on 1.14.4
The coords of the portal I built in the nether are 424 ~ 478

![2019-11-19_18 06 37](https://user-images.githubusercontent.com/57961449/69175557-df70c480-0afb-11ea-90da-6bfa4f4bbc3e.png)
![2019-11-19_18 22 10](https://user-images.githubusercontent.com/57961449/69175558-e0095b00-0afb-11ea-97ba-6f3a33a6e7c2.png)

**Comment by misode** [comment]
Cooler Caves replaces lava lakes with water because (1) lava doesn't fit in snowy caves and (2) the lava would otherwise melt the ice around it. However chunks aren't processed all in the same tick. This could sometimes create obsidian borders between chunks. Thus I decided to also replace all obsidian with water.

There are 3 possible fixes:
1. Don't replace lava lakes with water
2. Replace lava lakes with obsidian instead of water
3. Only replace obsidian if it doesn't have a nether portal next to it.
    - This would be the ideal solution, but it would require more difficult block scanning.

@sparks0 @SpecialBuilder32 @Bloo-dev I'd like to get your opinion on this.

**Comment by Nathan22211** [comment]
maybe don't replace obsidian

**Comment by misode** [comment]
> maybe don't replace obsidian

@Nathan22211 That's not possible because of this:
> This could sometimes create obsidian borders between chunks

**Comment by misode** [comment]
@sparks0 @Bloo-dev @SpecialBuilder32 Bump

**Comment by Bloo-dev** [comment]
Interesting. I don't see an easy way of fixing this and would just leave it in.
