### ISSUE TITLE
Arborenda leaving temporary marker sometimes

### ISSUE THREAD

**Issue by Dennis-0** [Gamemode4Dev/GM4_Datapacks#756]
**Describe the bug**
A marker with the tag `gm4_arborenda_trunk` was left behind in the world, preventing an armour stand from being placed in this position in this case

**To Reproduce**
Unknown

**Expected behavior**
The marker should've been removed immediately

**Fix**
Unknown

**Environment**
 - Minecraft version: 1.18.1
 - Server: GM4 Public Server

**Additional context**
It seems like the marker was removed when Arborenda was used again elsewhere on the server. This also destroyed a block below the marker that was placed by the player after using Arborenda.

**Comment by Bloo-dev** [comment]
I've figured out how to reproduce this:

**To Reproduce**
Steps to reproduce the behavior:
1. Place a single **unconnected** log
2. Break it with an Arborenda Axe (do not sneak!)
3. Place something else in that location
4. Use Arborenda on a tree somewhere in your world
5. The block in the previous location breaks as soon as Arborenda is used.

**Expected behavior**
The block in the first location should not break.

**Environment**
 - Minecraft version: 1.19
 - Installed Datapacks: Metallurgy

This bug is fixed in #795.
