### ISSUE TITLE
Lumos Shamir placing torches inside water*

### ISSUE THREAD

**Issue by jackythejack13** [Gamemode4Dev/GM4_Datapacks#763]
**Describe the bug**
Places torches while holding a Pickaxe with Lumos. Replacing torches inside water in the dark

**To Reproduce**
1. Cover yourself in water
2. Hold a pickaxe with Lumos with torches in your inventory
3. Torches keep getting replaced and broken by water

**Expected behavior**
Torches should not be placed in water at a darkness level

**Fix**
Add a if the player is in water, not to place torch

**Environment**
 - Minecraft version: 1.18.1
 - Server version: Gamemode 4 Public server 8
 - Installed Datapacks: Lumos
 - Installed Mods: Fabric

**Comment by Dennis-0** [comment]
This is caused by the block tag #gm4:replaceable, which contains all blocks the player can directly replace with blocks (like torches). It's intended to copy the same behaviour as a player trying to place the torch, so technically it's working as intended, but I can see this should be prevented.

Note that Crossbow Cartridges _should_ use the same conditions for placing a torch. It currently places the torch in water as well, but it's not too big of a problem because it's not repeatedly like with lumos.
