### ISSUE TITLE
Block Compressors React to Spectators

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#934]
**Describe the bug**
The Purpur pressure plate on top of Block Compressors reacts to players in spectator mode flying into it.

**To Reproduce**
1. Place a Block Compressor
2. Switch to spectator mode
3. Fly over the Block Compressor
4. Notice that the Purpur pressure plate is depressed.

**Expected behavior**
Spectator players should be ignored.

**Environment**
 - Minecraft version: 1.20.4

**Comment by BluePsychoRanger** [comment]
This bug was brought up during the machine block changes. Making it explicitly ignore spectator players would slightly decrease performance due to extra checks; right now it just checks for any entity, but to check for a non-spectator player, it'd need an extra check. 

Last time it was brought up it was decided that it wasn't that necessary to fix this bug, but the performance hit probably wouldn't be that much.
