### ISSUE TITLE
Ziprails feature request : A way to configure the speed perhaps ?

### ISSUE THREAD

**Issue by uczpre** [Gamemode4Dev/GM4_Datapacks#994]
While fine for vanilla minecraft , i am using it on a server with a mod that more than doubles the speed of minecarts.
this causes the ziprails to be more of a drag , i think the mod should have a configurable value perhaps through a /command to change the speed.
i would be very happy if this feature gets added :D , pls.

**Comment by misode** [comment]
We're not sure that a configuration feature like this is within scope of our project, since it is highly specific to this mod you're using.

Would you be able to modify the data pack to match your needs? The relevant changes are in [data/gm4_ziprails/functions/ziprail/zipping.mcfunction](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/master/gm4_ziprails/data/gm4_ziprails/functions/ziprail/zipping.mcfunction#L15-L18), on lines 15 to 18, where you'll want to change the `0.4` to a value that is close to the max minecart speed on your server.

**Comment by uczpre** [comment]
Thanks man ! i cant see why i cant do that ;D

i assume the -0.4's are also modified y ?
so if i want to turn the speed into 0.8 blocks/tick , it should look something like :

data merge entity @s[tag=gm4_taut_link, tag=gm4_zipping_north] {Motion:[0.0d,0.06d,-0.8d]}
data merge entity @s[tag=gm4_taut_link, tag=gm4_zipping_south] {Motion:[0.0d,0.06d,0.8d]}
data merge entity @s[tag=gm4_taut_link, tag=gm4_zipping_east] {Motion:[0.8d,0.06d,0.0d]}
data merge entity @s[tag=gm4_taut_link, tag=gm4_zipping_west] {Motion:[-0.8d,0.06d,0.0d]}

?

**Comment by EpyonProjects** [comment]
Yes, that's correct.  The 0.4's are the XZ speeds, and the 0.6 Y keeps the minecart from falling based on the 2t clock speed

**Comment by uczpre** [comment]
that didnt work :/

ive tested it in vannila minecraft 1.20.1 , but the speed is still just under 8m/s

**Comment by Bloo-dev** [comment]
> ive tested it in vannila minecraft 1.20.1 , but the speed is still just under 8m/s

In vanilla, minecarts have a hard-coded speed cap that they can not exceed in any way, even if you give them more motion (except for teleportation).
